name: 'deel_dbt_modeling'
version: '1.0.0'
config-version: 2

profile: 'deel_snowflake'

# Paths to relevant directories
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]
target-path: target  # directory which will store compiled SQL files
clean-targets:  # directories to be removed by `dbt clean`
  - target
  - dbt_modules

# Configuring models
models:
  deel_dbt_project:
    marts:
      +schema: marts
      +materialized: table
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: ephemeral
