name: 'deel_dbt_modeling'
version: '1.0.0'
config-version: 2

profile: 'deel_snowflake'

models:
  deel_dbt_modeling:
    # Staging models: Raw data ingestion and basic transformations
    staging:
      +schema: staging
      +materialized: view
      +tags: ['staging']
      
    # Intermediate models: Business logic and calculated fields
    intermediate:
      +schema: intermediate
      +materialized: ephemeral
      +tags: ['intermediate']
    
    # Marts models: Finalized tables used for analytics and reporting
    marts:
      +schema: marts
      +materialized: table
      +tags: ['marts']

seeds:
  deel_dbt_modeling:
    +schema: raw
    +tags: ['seeds']

snapshots:
  deel_dbt_modeling:
    +schema: snapshots
    +tags: ['snapshots']

tests:
  +store_failures: true
  +schema: test_results

clean-targets:
  - "target"
  - "dbt_packages"

quoting:
  database: false
  schema: false
  identifier: false
