name: 'deel_dbt_modeling'
version: '1.0.0'
config-version: 2

profile: 'deel_snowflake'

# Paths to relevant directories
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]
target-path: target  # directory which will store compiled SQL files
clean-targets:  # directories to be removed by `dbt clean`
  - target
  - dbt_modules

# Configuring models
models:
  deel_dbt_project:
    marts:
      +schema: marts
      +materialized: table
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate

seeds:
  deel_dbt_project:
    +schema: raw
    +docs:
      node_color: "#CF4647"
    globepay_chargeback_report:
      +description: "Contains chargeback transactions from Globepay, tracking refunded amounts and reasons."
      +column_types:
          external_ref: string
          chargeback_date: date
          chargeback_amount: numeric
          reason: string
    globepay_acceptance_report:
      +description: "Includes acceptance and declined transaction data from Globepay, along with country and currency details."
      +column_types:
          external_ref: string
          country: string
          total_transactions: int
          accepted_transactions: int
          declined_transactions: int

