deel_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "<your_snowflake_account>"
      user: "<your_snowflake_user>"
      password: "<your_snowflake_password>"
      role: "<your_snowflake_role>"
      database: "<your_snowflake_database>"
      warehouse: "<your_snowflake_warehouse>"
      schema: dbt_dev
      threads: 4

    prod:
      type: snowflake
      account: "<your_snowflake_account>"
      user: "<your_snowflake_user>"
      password: "<your_snowflake_password>"
      role: "<your_snowflake_role>"
      database: "<your_snowflake_database>"
      warehouse: "<your_snowflake_warehouse>"
      schema: dbt_prod
      threads: 8
